### ISSUE TITLE
Erreur de la phrase d'affichage du résultat - Mauvais opérateur

### ISSUE THREAD

**Issue by AntoineRoulinCPNV** [NicolasGlassey/226_Calculator#1]
@NicolasGlassey

Pour l'affichage de tout les résultats le mot "sum" ne change pas en fonction de l'opération effectuée.

Voici l'erreur présente dans le fichier Program.cs à la ligne 63 dans le projet d'origine sur le github.

`Console.WriteLine("The sum of " + operand1 + " and " + operand2 + " is : " + result);`

**Comment by NicolasGlassey** [comment]
@AntoineRoulinCPNV 

Bonjour Antoine,

J'ai apporté les modifications (basiques) permettant d'afficher correctement le calcul ainsi que son résultat, indépendemmment de l'opérateur utilisé.

Vous diposez, sur la branche main, du hotfix demandé.

Merci pour votre issue !
